# Set Number of Threads
/run/numberOfThreads 1

# Set electron solvation process: "Meesungnoen2002", "Ritchie1994", "Terrisol1990"
/process/dna/e-SolvationSubType Meesungnoen2002

# Chemistry Scavenger Cocentrations
# Units are assumed to be mol/dm3 (M)
/chem/scavenger/DMSO   5e-4
/chem/scavenger/Oxygen 0.27e-3

# Register Physics and Chemistries
/physics/SetPhysics   G4EmDNAPhysics_option2
/physics/SetChemistry G4EmDNAChemistry_userOption

# DNA Settings (Before Initialize)
/det/DNAFile  data/json/nuc-SASA.json
/det/OffSetFile  data/offsets/offsets.txt
/det/UseDNAVolumes True
/det/NbOfDNA 1
/det/CheckOverlaps False

# World Size Settings
/det/WorldSize 1 um
/det/EnvelopeRadius 0.5 um

/run/initialize

# Energy setting
/fpGun/setEnergy 2.5 keV
/fpGun/setPosition -30. 0. 0. angstrom
/fpGun/setDirection 1 0 0

# Number of primaries per event 
# Correlates with accumulated dose.
/fpGun/PrimariesPerEvent 1

# Chemistry Scheduler Settings
#/scheduler/endTime 1 picosecond
#/scheduler/endTime 1 nanosecond
#/scheduler/endTime 10 nanosecond
#/scheduler/endTime 100 nanosecond
#/scheduler/endTime 1 microsecond
#/scheduler/endTime 10 microsecond
/scheduler/endTime 100 microsecond
#/scheduler/endTime 1 millisecond
/scorer/species/nOfTimeBins 100

/scorer/species/addTimeToRecord 10 picosecond
/scorer/species/addTimeToRecord 100 picosecond
/scorer/species/addTimeToRecord 1 nanosecond
/scorer/species/addTimeToRecord 10 nanosecond
/scorer/species/addTimeToRecord 100 nanosecond
/scorer/species/addTimeToRecord 1 microsecond
/scorer/species/addTimeToRecord 10 microsecond
/scorer/species/addTimeToRecord 100 microsecond
#/scorer/species/addTimeToRecord 1 millisecond

# GValues: Output Options
/scorer/species/OutputFile data/species/SpeciesInfo
/scorer/species/OutputFormat ASCII 

# SB: Output Options
/scorer/StrandBreak/OutputFile data/strand_breaks/StrandBreakInfo
/scorer/StrandBreak/OutputFormat ASCII
/scorer/StrandBreak/BreakEnergy 17.5 eV

# Verbose Settings
/tracking/verbose 0
/scheduler/verbose 0

# Print Chemistry
/chem/reaction/print

# Run
/run/printProgress 1
/run/beamOn 10
