# Set Number of Threads
/run/numberOfThreads 1

# Set electron solvation process: "Meesungnoen2002", "Ritchie1994", "Terrisol1990"
/process/dna/e-SolvationSubType Meesungnoen2002

/process/chem/TimeStepModel IRT
#/process/chem/TimeStepModel SBS
#/process/chem/TimeStepModel IRT_syn

# Chemistry Scavenger Cocentrations
# Units are assumed to be mol/dm3 (M)
/chem/scavenger/setDMSOMole   5e-4
/chem/scavenger/setOxygenMole 0.27e-3

# Register Physics and Chemistries
/physics/setPhysics   G4EmDNAPhysics_option2
/physics/setChemistry G4EmDNAChemistry_userOption

# DNA Settings (Before Initialize)
/det/setDNAFile  data/json/nuc-SASA.json
/det/setOffsetFile  data/offsets/offsets.txt
/det/enableDNAVolumes True
/det/setNumberOfDNA 1
/det/checkOverlaps False

# World Size Settings
/det/setWorldSize 5 um
/det/setEnvelopeDiameter 5.0 um

/run/initialize

# Irradiation setting (spherical position)
/fpGun/setIrradiationType spherical
/fpGun/setEnergy 30 keV
/fpGun/setSphereRadius 200 angstrom

# Irradiation setting (fixed position)
#/fpGun/setIrradiationType fixed
#/fpGun/setEnergy 30 keV
#/fpGun/setPosition -30. 0. 0. angstrom
#/fpGun/setDirection 1 0 0

# Number of primaries per event 
# Correlates with accumulated dose.
/fpGun/setPrimariesPerEvent 1

# Chemistry Scheduler Settings
#/scheduler/endTime 1 picosecond
#/scheduler/endTime 1 nanosecond
#/scheduler/endTime 10 nanosecond
#/scheduler/endTime 100 nanosecond
#/scheduler/endTime 1 microsecond
/scheduler/endTime 10 microsecond
#/scheduler/endTime 100 microsecond
#/scheduler/endTime 1 millisecond
/scorer/species/setNumberOfTimeBins 100

/scorer/species/addTimeToRecord 10 picosecond
/scorer/species/addTimeToRecord 100 picosecond
/scorer/species/addTimeToRecord 1 nanosecond
/scorer/species/addTimeToRecord 10 nanosecond
/scorer/species/addTimeToRecord 100 nanosecond
/scorer/species/addTimeToRecord 1 microsecond
/scorer/species/addTimeToRecord 10 microsecond
#/scorer/species/addTimeToRecord 100 microsecond
#/scorer/species/addTimeToRecord 1 millisecond

# GValues: Output Options
/scorer/species/setOutputFile data/species/SpeciesInfo
/scorer/species/setOutputFormat root 

# SB: Output Options
/scorer/StrandBreak/setOutputFile data/strand_breaks/StrandBreakInfo
/scorer/StrandBreak/setOutputFormat root
/scorer/StrandBreak/setBreakEnergy 17.5 eV

# Position of Species at Each Timestep
/speciesPos/setEventNumToRecord 10
/speciesPos/setOutputFile data/species/SpeciesDist
/speciesPos/setOutputFormat root

# Verbose Settings
/tracking/verbose 0
/scheduler/verbose 0

# Print Chemistry
/chem/reaction/print

# Run
/run/printProgress 1
/run/beamOn 10
