# Set Number of Threads
/run/numberOfThreads 1

# Set electron solvation process: "Meesungnoen2002", "Ritchie1994", "Terrisol1990"
/process/dna/e-SolvationSubType Ritchie1994

# Chemistry Scavenger Settings
/chem/scavenger/setDMSOMole   5e-4
/chem/scavenger/setOxygenMole 0.27e-3

# Register Physics and Chemistries
/physics/setPhysics   G4EmDNAPhysics_option4
/physics/setChemistry G4EmDNAChemistry_userOption

# DNA Settings (Befor Initialize)
/det/setDNAFile  data/json/nuc-SASA.json
/det/setOffsetFile  data/offsets/offsets.txt
/det/enableDNAVolumes True
/det/setNumberOfDNA 1
/det/checkOverlaps False

# World Size Settings
/det/setWorldSize 1 um
/det/setEnvelopeDiameter 1.0 um

/run/initialize

# Energy setting
/fpGun/setEnergy 2.5 keV

# Number of primaries per event 
# Correlates with Dose per Event.
/fpGun/setPrimariesPerEvent 1

# Chemistry Scheduler Settings
/scheduler/endTime 100 microsecond
/scorer/species/setNumberOfTimeBins 100
/scorer/species/addTimeToRecord 1 microsecond
/scorer/species/addTimeToRecord 10 microsecond

# GValues: Output Options
/scorer/species/setOutputFile data/species/SpeciesInfo
/scorer/species/setOutputFormat root 

# SB: Output Options
/scorer/StrandBreak/setOutputFile data/strand_breaks/StrandBreakInfo
/scorer/StrandBreak/setOutputFormat root
/scorer/StrandBreak/setBreakEnergy 17.5 eV

# Verbose Settings
/tracking/verbose 0
/scheduler/verbose 0

# Print Chemistry
/chem/reaction/print

/control/execute vis.mac

# Run
/run/printProgress 1
/run/beamOn 0